### ISSUE TITLE
Apprentice Video does not contain any version numbers on macOS

### ISSUE THREAD

**Issue by core-code** [pkoshevoy/aeyae#5]
both the CFBundleShortVersionString and CFBundleVersion entry in the Info.plist file are empty.

all macOS apps are supposed to contain valid version information.

**Comment by pkoshevoy** [comment]
`This key is required by the App Store and is used throughout the system to identify your app's released or unreleased build.`

I don't offer anything through the app store

**Comment by core-code** [comment]
of course Apple can only make 'requirements' for apps distributed inside the Mac App Store. apps not distributed there can just crash all the time for all for all Apple cares - this doesn't mean crashing is a good idea.

users certainly expect each proper Mac app to have a proper version number that can be viewed in the Finder. this means adding athe CFBundleShortVersionString and CFBundleVersion keys. 

the CFBundleVersion key is especially important as it defines which version will be launched when multiple versions are installed. obviously the newest one should be launched. the operating system can only determine 'newest' if the 'CFBundleVersion' key is properly populated with a version number or build number.

also, the CFBundleGetInfoString has been deprecated for more than 10 years and should be removed.

**Comment by pkoshevoy** [comment]
I still provide builds for OSX 10.5 PPC, so I think I'll keep CFBundleGetInfoString

**Comment by pkoshevoy** [comment]
I'll look into adding CFBundleVersion

**Comment by core-code** [comment]
awesome thanks

**Comment by pkoshevoy** [comment]
Fixed in git.replay.20190804.133243.5f5c8e6

**Comment by core-code** [comment]
i can confirm this is fixed, thanks
